name: CD PowerShell Gallery

on:
  push:
    branches: ["main", "develop"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch unshallow
        run: git fetch --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Run GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Apply version to PSAxDevKit manifest
        shell: pwsh
        run: |
          $version = "${{ env.GitVersion_MajorMinorPatch }}"
          $prerelease = "${{ env.GitVersion_NuGetPreReleaseTagV2 }}"
          $manifestFile = Get-ChildItem ".\src\Modules\PSAxDevKit\PSAxDevKit.psd1"
          $content = Get-Content $manifestFile -Raw
          $content = $content.Replace("[[version]]", $version);
          $content = $content.Replace("[[prerelease]]", $prerelease);
          Set-Content -Value $content -Path $manifestFile

      - name: Install all dependencies
        shell: pwsh
        run: .\src\Modules\PSAxDevKit\setup\PreInstall.ps1

      - name: Publish PSAxDevKit to PowerShell Gallery
        shell: pwsh
        run: Publish-Module -Path .\src\Modules\PSAxDevKit\ -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_NUGET_APIKEY }}